spring.application.name=ChatbotAi
#spring.datasource.url=jdbc:postgresql://localhost:5432/test
#spring.datasource.username=postgres
#spring.datasource.password=2003
spring.datasource.url=jdbc:postgresql://pg-38718e92-narayana070203-0067.d.aivencloud.com:22968/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_PUlewF6F-RL8qV1-3v3
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=root
spring.securit.user.password=password
spring.app.jwtSecret=dfggkjshgfksksdhvcXyZ123abcQwertyUiop
spring.app.jwtExpirationMs=86400000

spring.app.imageBasePath=https://res.cloudinary.com/dvniqmmy3/raw/upload/v1774174628/chatBotDoc/

spring.jpa.open-in-view=false

cloudinary.cloud_name=dvniqmmy3
cloudinary.api_key=429454987439389
cloudinary.api_secret=DnrLSXmdYh2rJ8i9AwHoYpcbOas


# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.file-size-threshold=2MB

# Tomcat-specific file upload limits
server.tomcat.max-http-form-post-size=50MB
server.tomcat.max-swallow-size=50MB

# This is the key property for file count limit in Tomcat
server.tomcat.max-parameter-count=10000
server.tomcat.max-part-count=100

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
#spring.ai.ollama.chat.options.model=qwen2.5:3b
spring.ai.ollama.embedding.options.model=mxbai-embed-large

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1024

spring.jvm.args=--enable-native-access=ALL-UNNAMED
